title: tvardy.blog
description: >-
  A developers' website to share some thoughts, ideas, code, an official resume etc.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tvardy.blog" # the base hostname & protocol for your site, e.g. http://example.com
author: tvardy
lang: en
timezone: UTC
excerpt_separator: "<!-- more -->"
#google_analytics:
#comments: false

markdown: kramdown
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - octopress-minify-html

permalink: "/blog/:year/:month/:day/:title/"

pagination:
  enabled: true
  debug: true
  collection: "posts"
  per_page: 3
  permalink: "/blog/:num/"
  title: "Archive page :num | :title"
  sort_reverse: true

kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

jekyll-archives:
  enabled:
    - tags
  layout: category_archives
  permalinks:
    tag: /blog/tag/:name/

include:
  - _redirects

exclude:
  - .idea/
  - Gemfile
  - Gemfile.lock
  - README.md
  #- node_modules
  #- vendor/bundle/
  #- vendor/cache/
  #- vendor/gems/
  #- vendor/ruby/
