# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: tvardy.blog
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A developers' website to share some thoughts, ideas, code, an official resume etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tvardy.blog" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: TheTvardy
github_username:  tvardy
author: tvardy

# Build settings
safe: true
markdown: kramdown
theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-minify-html

permalink: /blog/:year/:month/:day/:title/
paginate_path: /blog/:num/
paginate: 3

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /blog/cat/:name/
    tag: /blog/tag/:name/

include:
  - _redirects

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .idea/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
