name: CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          path: |
            __sapper__
            data
            public
            package.json
            package-lock.json
            app.js

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          connect_timeout: 10s
          first_ssh: |
            rm -rf ${{ secrets.DC_PATH }}
          scp: |
            './artifact/*' => ${{ secrets.DC_PATH }}
          last_ssh: |
            cd ${{ secrets.DC_PATH }}
            ${{ secrets.DC_NPM_BIN }} ci --production
            ln -fs ../.env ./.env
            ${{ secrets.DC_FINISH }}
