name: CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        env:
          cache-name: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm i -g npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          path: |
            __sapper__
            data
            public
            package.json
            package-lock.json
            app.js
            pm_*.sh

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          connect_timeout: 5s
          first_ssh: |
            rm -rf ${{ secrets.DC_PATH }}
          scp: |
            './artifact/*' => ${{ secrets.DC_PATH }}
          last_ssh: |
            cd ${{ secrets.DC_PATH }}
            npm ci --production
            ln -fs ../.env ./.env.production
            bash ./pm_restart.sh
